apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${REDIS_PV_NAME}
  labels:
    "cosmotech.com/service": "redis"
spec:
  storageClassName: ""
  claimRef:
    name: "${REDIS_PVC_NAME}"
    namespace: "${NAMESPACE}"
  capacity:
    storage: ${REDIS_DISK_SIZE}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    volumeHandle: ${REDIS_DISK_RESOURCE}
    volumeAttributes:
      fsType: ext4
