apiVersion: v1
kind: PersistentVolume
metadata:
  name: cosmotech-database-master-pv
  labels:
    "cosmotech.com/service": "redis"
spec:
  capacity:
    storage: ${REDIS_DISK_SIZE}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    volumeHandle: ${REDIS_DISK_RESOURCE}
    volumeAttributes:
      fsType: ext4
