apiVersion: v1
kind: Pod
metadata:
  name: migration-pod
spec:
  containers:
  - name: migration-pod
    image: ghcr.io/cosmo-tech/mock-migrate:latest
    env:
    - name: COSMOS_DB
      value: ${COSMOS_DB}
    - name: COSMOS_URI
      value: ${COSMOS_URI}
    - name: COSMOS_KEY
      value: ${COSMOS_KEY}
    - name: API_SCOPE
      value: ${API_SCOPE}
    - name: API_URL
      value: ${API_URL}
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "cosmotech"
    effect: "NoSchedule"
  restartPolicy: Never
  initContainers:
  - name: download-dependancies
    image: alpine:latest
    command: [ "sh", "-c", "apk add --no-cache curl && curl -L https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq" ]
    # volumeMounts:
    # - name: config-volume
    #   mountPath: /path/to/my
    securityContext: