apiVersion: v1
kind: Pod
metadata:
  name: migration-pod
spec:
  containers:
  - name: migration-pod
    image: ghcr.io/cosmo-tech/mock-migrate:latest
    env:
    - name: COSMOS_DB
      value: ${COSMOS_DB}
    - name: COSMOS_URI
      value: ${COSMOS_URI}
    - name: COSMOS_KEY
      value: ${COSMOS_KEY}
    - name: API_SCOPE
      value: ${API_SCOPE}
    - name: API_URL
      value: ${API_URL}
  nodeSelector:
    "cosmotech.com/tier": "db"
  tolerations:
  - key: "vendor"
    operator: "Equal"
    value: "cosmotech"
    effect: "NoSchedule"
  restartPolicy: Never