{
 "title": "Cosmo Tech licensing v2",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Organization",
    "query": {
     "query": "label_values(cosmotech_findAllScenarios_total, organizationId)"
    }
   },
   {
    "name": "workspace",
    "label": "Workspace",
    "query": {
     "query": "label_values(cosmotech_findAllScenarios_total{organizationId=~\"$Organization\"}, workspaceId)"
    }
   },
   {
    "name": "Usersquery",
    "label": "Users",
    "query": {
     "query": "label_values(cosmotech_findAllScenarios_total{organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}, user)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total distinct users",
   "type": "stat",
   "description": "Count of unique users, eliminating duplicates",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "cosmotech_findAllScenarios_total{user=~\"$Usersquery\", organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily user sign in (Not accurate)",
   "type": "timeseries",
   "description": "Daily count of user sign-ins via the web app",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by(time) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$Usersquery\", organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Users sign in (Not accurate)",
   "type": "stat",
   "description": "Inclusive count of unique user sign-ins",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (time) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$Usersquery\", organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sign in per User  (Not accurate)",
   "type": "piechart",
   "description": "Cumulative sign-ins via web app + scenarios deletion per user over time",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$Usersquery\", organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Daily sign in per User  (Not accurate)",
   "type": "timeseries",
   "description": "Evolution of distinct user sign-ins via web app over time",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum by (user) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$Usersquery\", organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total API requests per organization  (Not accurate)",
   "type": "piechart",
   "description": "Combined count of API requests for web app sign-ins and scenario deletions",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (organizationId) (increase({__name__=~\"cosmotech_findAllScenarios_total\", user=~\"$Usersquery\", organizationId=~\"$Organization\", workspaceId=~\"$workspace\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cumulated scenario runs (No filters)",
   "type": "timeseries",
   "description": "\t\nCumulative scenario runs over time, no filters except time range",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 22 },
   "targets": [
    {
     "command": "ts.range",
     "filter": "usage=licensing name=run",
     "keyName": "ts:metric:cosmotech:scenariorun:run:total:ds",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Maximum of parallel scenario run on period  (No filters)",
   "type": "stat",
   "description": "Peak simultaneous scenario runs, no filters except time range",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucket": 31536000000,
     "command": "ts.range",
     "keyName": "ts:metric:cosmotech:scenariorun:running:total:ds",
     "type": "timeSeries"
    }
   ]
  },
  {
   "title": "Simultaneous  scenario runs (No filters)",
   "type": "timeseries",
   "description": "\t\nTotal of parallel scenario runs over time, no filters except time range",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 32 },
   "targets": [
    {
     "command": "ts.range",
     "filter": "usage=licensing name=run",
     "keyName": "ts:metric:cosmotech:scenariorun:running:total:ds",
     "type": "timeSeries"
    }
   ]
  }
 ]
}